"""add report status

Revision ID: 260b04c5fa14
Revises: cc2ab7b1993c
Create Date: 2026-05-19 02:21:29.719201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '260b04c5fa14'
down_revision: Union[str, None] = 'cc2ab7b1993c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Backfill existing rows as 'complete' (they already have file_path),
    # then drop the server_default so future inserts must set the value.
    op.add_column(
        'reports',
        sa.Column(
            'status',
            sa.String(length=50),
            nullable=False,
            server_default='complete',
        ),
    )
    op.alter_column('reports', 'status', server_default=None)
    op.add_column('reports', sa.Column('error_message', sa.Text(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'error_message')
    op.drop_column('reports', 'status')
    # ### end Alembic commands ###
