"""add model_pricing

Revision ID: b5d78c85d87a
Revises: 7ef833387fd7
Create Date: 2026-05-16 03:38:46.648627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b5d78c85d87a'
down_revision: Union[str, None] = '7ef833387fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_key', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('prompt_cost_per_1k', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('completion_cost_per_1k', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_pricing_model_key'), 'model_pricing', ['model_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_pricing_model_key'), table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
