"""add last_synced_at

Revision ID: d679b4720b25
Revises: b5d78c85d87a
Create Date: 2026-05-16 03:41:43.808379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd679b4720b25'
down_revision: Union[str, None] = 'b5d78c85d87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_pricing', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_pricing', 'last_synced_at')
    # ### end Alembic commands ###
